name: mpro-minecraft-plugins - Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Extract version from pom.xml
      - name: Extract version from pom.xml
        id: get-version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Create GitHub release
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.version }}
          release_name: mpro-minecraft-plugins v${{ env.version }}
          draft: false
          prerelease: ${{ contains(env.version, '-ALPHA') || contains(env.version, '-BETA') }}

      # Upload artifact to release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/MproMinecraftPlugins-${{ env.version }}-shaded.jar
          asset_name: mpro-minecraft-plugins-${{ env.version }}.jar
          asset_content_type: application/java-archive
