name: mpro-minecraft-plugins - build and release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0-ALPHA)'
        required: true
        default: '1.0-ALPHA'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      version: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Echo version
        run: |
          echo "Version: ${{ github.event.inputs.version }}"

      - name: Build with Maven
        run: |
          echo "Starting Maven build..."
          mvn clean package
          echo "Maven build complete."

      - name: Debug target directory
        run: |
          echo "Listing target directory contents:"
          ls -la ${{ github.workspace }}/target

      - name: Check if artifact exists
        run: |
          if [ -f "${{ github.workspace }}/target/MproMinecraftPlugins-${{ github.event.inputs.version }}-shaded.jar" ]; then
            echo "Shaded JAR found."
          else
            echo "Shaded JAR not found. Build may have failed or the file name is incorrect."
            exit 1
          fi

      - name: Upload Build Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/assets
          asset_path: ${{ github.workspace }}/target/MproMinecraftPlugins-${{ github.event.inputs.version }}-shaded.jar
          asset_name: MproMinecraftPlugins-${{ github.event.inputs.version }}-shaded.jar
          asset_content_type: application/java-archive
