name: Build and Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0-ALPHA)'
        required: true
        default: '1.0-ALPHA'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      version: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Echo version
        run: echo "Version: ${{ github.event.inputs.version }}"

      - name: Build with Maven
        run: mvn clean package

      - name: Debug current directory
        run: pwd

      - name: Debug target directory
        run: ls -la ./target

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: mpro-minecraft-plugins v${{ github.event.inputs.version }}
          draft: false
          prerelease: true

      - name: Upload Build Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/MproMinecraftPlugins-${{ github.event.inputs.version }}-shaded.jar
          asset_name: MproMinecraftPlugins-${{ github.event.inputs.version }}-shaded.jar
          asset_content_type: application/java-archive
